### ISSUE TITLE
Undefined func / struct http.IndexStats

### ISSUE THREAD

**Issue by nooproblem** [blevesearch/bleve-explorer#7]
Hi,

When running go build in '~/go/src/github.com/blevesearch/bleve-explorer', the following error is generated:

```
./main.go:53: undefined: "github.com/blevesearch/bleve/http".IndexStats
```

This is the line in blevesearch/bleve-explorer/main.go that the error is referring to:

```
expvars.Set("indexes", bleveHttp.IndexStats())
```

However, as far as I am able to tell there is no function IndexStats() contained in blevesearch/bleve/http, but there is a struct IndexStat contained in blevesearch/bleve/index_stats.go.

Your thoughts / advice on how to resolve this issue will be greatly appreciated.

**Comment by mschoch** [comment]
Sorry, we refactored code in bleve and it broke bleve-explorer.  I had fixed it but forgot to push.  I just pushed up the changes.  Can you try again?

**Comment by nooproblem** [comment]
Hi,

Thank you very much for your quick reply.

I have deleted and pulled the most recent changes for bleve-explorer and bleve (inc. dependencies) and I have now been able to successfully compile and run the bleve-explorer binary.

However, now the following error is generated when performing a get request on 127.0.0.1:8095:

```
$ ./bleve-explorer 
2016/01/10 16:23:03 Listening on :8095
2016/01/10 16:23:12 http: panic serving [::1]:50552: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.(*conn).serve.func1(0xc820150000, 0xc6fd68, 0xc82002c258)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200ef620, 0xc820140880, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/np/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc6fee8, 0xc820150630, 0xc8200fcfc0, 0xc6e940, 0xc8200ef620, 0x673990, 0x1, 0x756ea1690a1a01)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200ec880, 0xc6fee8, 0xc820150630, 0xc8200fcfc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc6e968, 0xc8200ec880, 0xc6fee8, 0xc820150630, 0xc8200fcfc0)
    /Users/np/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200ec950, 0xc6fee8, 0xc820150630, 0xc8200fcfc0)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc6fee8, 0xc820150630, 0xc8200fcfc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200ef6e0, 0xc6fee8, 0xc820150630, 0xc8200fcfc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820013a40, 0xc6fee8, 0xc820150630, 0xc8200fcfc0)
    /Users/np/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820014870, 0xc6fee8, 0xc820150630, 0xc8200fcfc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82013a6c0, 0xc6fee8, 0xc820150630, 0xc8200fcfc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820150000)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
2016/01/10 16:23:12 http: panic serving [::1]:50553: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc820150790, 0xc6fd68, 0xc82002c2a8)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200ef620, 0xc820140c00, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/np/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc6fee8, 0xc820150840, 0xc8200fd0a0, 0xc6e940, 0xc8200ef620, 0x673990, 0x1, 0x756ea165c8ff01)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200ec880, 0xc6fee8, 0xc820150840, 0xc8200fd0a0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc6e968, 0xc8200ec880, 0xc6fee8, 0xc820150840, 0xc8200fd0a0)
    /Users/np/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200ec950, 0xc6fee8, 0xc820150840, 0xc8200fd0a0)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc6fee8, 0xc820150840, 0xc8200fd0a0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200ef6e0, 0xc6fee8, 0xc820150840, 0xc8200fd0a0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820013a40, 0xc6fee8, 0xc820150840, 0xc8200fd0a0)
    /Users/np/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820014870, 0xc6fee8, 0xc820150840, 0xc8200fd0a0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82013a6c0, 0xc6fee8, 0xc820150840, 0xc8200fd0a0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820150790)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
2016/01/10 16:23:12 http: panic serving [::1]:50554: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc8201509a0, 0xc6fd68, 0xc82002c2b0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200ef620, 0xc820140f80, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/np/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc6fee8, 0xc820150a50, 0xc8200fd180, 0xc6e940, 0xc8200ef620, 0x673990, 0x1, 0x756ea12be07901)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200ec880, 0xc6fee8, 0xc820150a50, 0xc8200fd180)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc6e968, 0xc8200ec880, 0xc6fee8, 0xc820150a50, 0xc8200fd180)
    /Users/np/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200ec950, 0xc6fee8, 0xc820150a50, 0xc8200fd180)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc6fee8, 0xc820150a50, 0xc8200fd180)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200ef6e0, 0xc6fee8, 0xc820150a50, 0xc8200fd180)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820013a40, 0xc6fee8, 0xc820150a50, 0xc8200fd180)
    /Users/np/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820014870, 0xc6fee8, 0xc820150a50, 0xc8200fd180)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82013a6c0, 0xc6fee8, 0xc820150a50, 0xc8200fd180)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8201509a0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
2016/01/10 16:23:12 http: panic serving [::1]:50555: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc820150bb0, 0xc6fd68, 0xc82002c2b8)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200ef620, 0xc820141300, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/np/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc6fee8, 0xc820150c60, 0xc8200fd260, 0xc6e940, 0xc8200ef620, 0x673990, 0x1, 0x756ea1107ba601)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200ec880, 0xc6fee8, 0xc820150c60, 0xc8200fd260)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:483 +0x19c
main.myFileHandler.ServeHTTP(0xc6e968, 0xc8200ec880, 0xc6fee8, 0xc820150c60, 0xc8200fd260)
    /Users/np/go/src/github.com/blevesearch/bleve-explorer/http_util.go:59 +0xb5
main.(*myFileHandler).ServeHTTP(0xc8200ec950, 0xc6fee8, 0xc820150c60, 0xc8200fd260)
    <autogenerated>:7 +0xb6
net/http.StripPrefix.func1(0xc6fee8, 0xc820150c60, 0xc8200fd260)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1455 +0x1a5
net/http.HandlerFunc.ServeHTTP(0xc8200ef6e0, 0xc6fee8, 0xc820150c60, 0xc8200fd260)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820013a40, 0xc6fee8, 0xc820150c60, 0xc8200fd260)
    /Users/np/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820014870, 0xc6fee8, 0xc820150c60, 0xc8200fd260)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82013a6c0, 0xc6fee8, 0xc820150c60, 0xc8200fd260)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820150bb0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
```

Also, the following error is generated when performing a get request on 127.0.0.1:8095/indexes:

```
./bleve-explorer
2016/01/10 16:27:26 Listening on :8095
2016/01/10 16:27:43 http: panic serving [::1]:50659: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.(*conn).serve.func1(0xc82014e000, 0xc6fde8, 0xc82002c280)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200ef620, 0xc82013c840, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/np/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc6ff68, 0xc82014e0b0, 0xc8200fae00, 0xc6e7a8, 0xc8200ef620, 0x673990, 0x1, 0xb1bc01)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200ec8a0, 0xc6ff68, 0xc82014e0b0, 0xc8200fae00)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:483 +0x19c
main.RewriteURL.func1(0xc6ff68, 0xc82014e0b0, 0xc8200fae00)
    /Users/np/go/src/github.com/blevesearch/bleve-explorer/http_util.go:65 +0x93
net/http.HandlerFunc.ServeHTTP(0xc8200ef9e0, 0xc6ff68, 0xc82014e0b0, 0xc8200fae00)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820013bd0, 0xc6ff68, 0xc82014e0b0, 0xc8200fae00)
    /Users/np/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820014870, 0xc6ff68, 0xc82014e0b0, 0xc8200fae00)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc8201386c0, 0xc6ff68, 0xc82014e0b0, 0xc8200fae00)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82014e000)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
2016/01/10 16:27:43 http: panic serving [::1]:50660: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc82014e4d0, 0xc6fde8, 0xc82002c2b8)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200ef620, 0xc82013cbc0, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/np/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc6ff68, 0xc82014e580, 0xc8200faee0, 0xc6e7a8, 0xc8200ef620, 0x673990, 0x1, 0xb1bc01)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200ec8a0, 0xc6ff68, 0xc82014e580, 0xc8200faee0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:483 +0x19c
main.RewriteURL.func1(0xc6ff68, 0xc82014e580, 0xc8200faee0)
    /Users/np/go/src/github.com/blevesearch/bleve-explorer/http_util.go:65 +0x93
net/http.HandlerFunc.ServeHTTP(0xc8200ef9e0, 0xc6ff68, 0xc82014e580, 0xc8200faee0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820013bd0, 0xc6ff68, 0xc82014e580, 0xc8200faee0)
    /Users/np/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820014870, 0xc6ff68, 0xc82014e580, 0xc8200faee0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc8201386c0, 0xc6ff68, 0xc82014e580, 0xc8200faee0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82014e4d0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
2016/01/10 16:27:43 http: panic serving [::1]:50661: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc82014e6e0, 0xc6fde8, 0xc82002c2c0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc8200ef620, 0xc82013cf40, 0x11, 0x0, 0x0, 0x0, 0x0)
    /Users/np/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc6ff68, 0xc82014e790, 0xc8200fafc0, 0xc6e7a8, 0xc8200ef620, 0x673990, 0x1, 0xb1bc01)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc8200ec8a0, 0xc6ff68, 0xc82014e790, 0xc8200fafc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/fs.go:483 +0x19c
main.RewriteURL.func1(0xc6ff68, 0xc82014e790, 0xc8200fafc0)
    /Users/np/go/src/github.com/blevesearch/bleve-explorer/http_util.go:65 +0x93
net/http.HandlerFunc.ServeHTTP(0xc8200ef9e0, 0xc6ff68, 0xc82014e790, 0xc8200fafc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820013bd0, 0xc6ff68, 0xc82014e790, 0xc8200fafc0)
    /Users/np/go/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.(*ServeMux).ServeHTTP(0xc820014870, 0xc6ff68, 0xc82014e790, 0xc8200fafc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc8201386c0, 0xc6ff68, 0xc82014e790, 0xc8200fafc0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82014e6e0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/server.go:1910 +0x3f6
```

Your thoughts / advice on how to resolve this issue will be greatly appreciated.

**Comment by mschoch** [comment]
Hmmn, indeed I get the same thing when working with a clean GOPATH.  Unfortunately I don't know how this bindata_assetfs thing works or why it might be failing.  Hey @steveyen do you have any ideas?

**Comment by nooproblem** [comment]
@mschoch just picking up on this again. Can you please advise, to the best of your knowledge, what commit/releases of bleve and bleve-explorer are compatible with each other? My thinking is I could use Masterminds/glide or rancher/trash along with go 1.5+'s dependency vendoring to resolve this issue for now. Thanks in advance!

**Comment by mschoch** [comment]
This issue should have been closed, the latest versions should all work.

But you're right we probably should move all the sample apps to be versioned with the new numbered releases of bleve.  I'll open higher-level issue for that.

**Comment by nooproblem** [comment]
Thanks for your help, it is greatly appreciated.
